apiVersion: v1
kind: Service
metadata: 
  name: postgres-service
  labels:
   app: postgres-service
spec:
 ports:
  - port: 5432
    targetPort: 5432
 selector:  
      name: postgres-deploy
      app: voting-app 
