apiVersion: v1
kind: Pod
metadata:
  name: postgres-deploy
  labels:
    app: voting-app
    name: postgres-deploy 



spec:
 containers:
   - name: postgres
     image: postgres  

     ports:
       - containerPort: 5432
     env:
       - name: POSTGRES_USER
         value: "postgres"
       - name: POSTGRES_PASSWORD
         value: "postgres"
