apiVersion: v1
kind: Pod
metadata:
  name: redis-deploy
  labels:
    app: voting-app
    name:  redis-deploy 



spec:
 containers:
   - name: redis-deploy
     image: redis  

     ports:
       - containerPort: 6379

