apiVersion: v1
kind: Service
metadata: 
 name: result-app-service
spec:
 type: NodePort
 ports: 
  - targetPort: 80
    port: 80
    nodePort: 30081
 selector: 
      app: voting-app
      name: result
