apiVersion: v1
kind: Pod
metadata:
 name: voting-app-deploy
 labels:
  app: voting-app
  name: result1
spec:
  containers:
     - name: voting-app
       image: kodekloud/examplevotingapp_vote:v1
       ports:
         - containerPort: 80
