apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    app: voting-app
    name: voting



spec:
 containers:
   - name: voting-app
     image: kodekloud/examplevotingapp_vote:v1

     ports:
       - containerPort: 80

